
version: "3"
services:
    app:
        build: .
        volumes:
            - .:/usr/src/app
        image: week3ws-app:latest
        restart: always
        ports:
            - 4026:3050
        command: node app7.js 


